MongoDBPool/Models/Results.cs
using System;

namespace MongoDBPool.Models
{

    public class Results 
    {
        public int _id { get; set; }
        public int HostId { get; set; }
        public int OppenentId { get; set; }     
        public DateTime Date  { get; set; }
        public int HosBallsLeft { get; set; }
        public int OppnetBallsLeft { get; set; }
        public string OppnetName { get; set; }
        public string HostName { get; set; }
        public int HostPoints { get; set; }
        public int OpponentPoints{ get; set; }
        public string HostStatus { get; set; }
        public string OppnentStatus { get; set; }

        public int BlackBallPayerId { get; set; }
        public int BlackBall { get; set; }


        public Results(){}

        public Results(int hostId, int oppId, DateTime date, int hosBal, int oppnetBall, int blackBallPayerId, int blackBall)
        {
            HostId = hostId;
            OppenentId = oppId;
            Date = date;
            HosBallsLeft = hosBal;
            OppnetBallsLeft = oppnetBall;
            BlackBallPayerId = blackBallPayerId;
            BlackBall = blackBall;

        }

        public Results(int id, int hostBallsLeft, int oppnentBallsLeft)
        {
            _id = id;
            HosBallsLeft = hostBallsLeft;
            OppnetBallsLeft = oppnentBallsLeft;
         
        }

    }
}

MongoDBPool/ViewModels/DisplayResultView.cs
using System.Collections.Generic;
using MongoDBPool.Models;

namespace MongoDBPool.ViewModels
{
    public class DisplayResultView
    {     
        public IList<Results> HostResults { set; get; }
      }
    }
    

MongoDBPool/Controllers/PlayerController.cs
using System.Linq;
using System.Web.Mvc;
using MongoDBPool.Models;
using MongoDBPool.Repository;
using MongoDBPool.Services;
using MongoDBPool.ViewModels;


namespace MongoDBPool.Controllers
{
     public class PlayerController : Controller
     {
        
         private readonly PlayerRepository _playerRop;   
         private readonly RegistorPlayerService _playerRegistrationService;
       
        public PlayerController()
        {
            _playerRop = new PlayerRepository();
         
            _playerRegistrationService = new RegistorPlayerService(new PlayerRepository(), new PlayerValidator());
        }

        public ActionResult Index()
        {
            return View(_playerRop.SelectAllAsList().OrderBy(x => x.FirstName));
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(PlayerCreateViewModel model)
        {       
              var player = new Player(model.FirstName, model.LastName, model.Age, model.EmailAddress);
              var emailMesage = _playerRegistrationService.PlayerRegistration(player).EmailAddress;
              if (emailMesage == "Player Email Already Exist ")
            {         
                ModelState.AddModelError("PlayerCheck", emailMesage);
                return View();        
            }
            
                return RedirectToAction("Index");                    
          }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            return View(_playerRop.SelectById(id));
        }

        [HttpPost]
        public ActionResult Edit(PlayerCreateViewModel model, FormCollection collection)
        {
            var player = new Player(int.Parse((collection["Id"])), model.FirstName, model.LastName, model.Age, model.EmailAddress);

            _playerRop.Update(player);

            return RedirectToAction("Index");
        }    
        
        [HttpGet]
        public ActionResult Delete(int id)
        {
           return View(_playerRop.SelectById(id));
        }

      [HttpPost, ActionName("Delete")]
        public ActionResult ConfirmDelete(int id) 
      {
        _playerRop.Delete(id);
        return RedirectToAction("Index");
      }
     }
}

MongoDBPool/Controllers/ResultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MongoDB.Bson;
using MongoDBPool.Models;
using MongoDBPool.Repository;
using MongoDBPool.Services;
using MongoDBPool.ViewModels;


namespace MongoDBPool.Controllers
{
    public class ResultController : Controller
    {
        //
        // GET: /Result/
        private readonly ResultRepository _resultRepo;
        private readonly PlayerRepository _playerRop;
        private readonly ResultsService _resultsService;

        public ResultController()
        {
            _resultRepo = new ResultRepository();
            _playerRop = new PlayerRepository();
            _resultsService = new ResultsService(new PlayerRepository(), new ResultRepository());
        }

        public ActionResult Index(string id)
        {

            return View(_resultRepo.SelectAllAsList());
        }

        [HttpGet]
        public ActionResult Edit(string id)
        {
            return View(_resultRepo.SelectById(int.Parse(id)));
        }

        [HttpPost]
        public ActionResult Edit(EditResultsView model, FormCollection collection)
        {
            var results = new Results(int.Parse((collection["_id"])), model.HostBallLeft, model.OppnentBallLeft);

            _resultRepo.Update(results);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult CreateResult(string id, FormCollection form)
        {
            //Get select player by id
            var currentPlayer = _playerRop.SelectById(int.Parse(id));
            //filtering players list
            var listOfPlayer = _playerRop.SelectAllAsList().Where(x => x.Id != int.Parse(id)).OrderBy(x => x.FirstName);
            var blackBallPlayer = _playerRop.SelectAllAsList().OrderBy(x => x.FirstName);
            var blackballplayerlist = blackBallPlayer.Select(x => new SelectListItem { Text = x.FirstName + " " + x.LastName, Value = x.Id.ToString(), Selected = false }).ToList();
            var selectList = listOfPlayer.Select(x => new SelectListItem{Text = x.FirstName + " " + x.LastName,Value = x.Id.ToString(),Selected = false}).ToList();
            //inserting markup tags for dropdown
            selectList.Insert(0, new SelectListItem { Selected = true, Text = "Choose", Value = "Choose" });
            blackballplayerlist.Insert(0, new SelectListItem { Selected = true, Text = "Choose", Value = "Choose" });

            var viewModel = new PlayerCreateViewModel() { SelectedPLayerValue = selectList, BalckBallPLayerValue = blackballplayerlist };
            viewModel.FirstName = currentPlayer.FirstName;
            viewModel.LastName = currentPlayer.LastName;
            viewModel.Age = currentPlayer.Age;
            viewModel.Id = currentPlayer.Id;
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult CreateResult(string id, PlayerCreateViewModel modelView, FormCollection form)
        {
            TryUpdateModel(modelView, form.ToValueProvider());
            var hostPlayer = _playerRop.SelectById(int.Parse(id));
            var opponent = _playerRop.SelectById(int.Parse(form["Opponent"]));
            var blackBallPlayer = _playerRop.SelectById(int.Parse(form["BlackBallPlayer"]));

            var newResult = new Results(hostPlayer.Id, opponent.Id, DateTime.Today, int.Parse(form["MyList1"]), int.Parse(form["MyList2"]),blackBallPlayer.Id, int.Parse(form["blackBall"]));
            _resultsService.ResultsEvaluation(newResult);
            _resultsService.CalculatePoints(newResult);

            ViewBag.id = id;

            return RedirectToAction("Index");

        }
        [HttpGet]
        public ActionResult DisplayResults(string id)
        {
            var viewModel = new DisplayResultView();
            viewModel.HostResults = _resultRepo.SelectAllResultsAsList(int.Parse(id));

            return View(viewModel);
        }



    }

    }

MongoDBPool/Views/Result/CreateResult.cshtml
@model MongoDBPool.ViewModels.PlayerCreateViewModel
           
@{
    ViewBag.Title = "CreateResult";
}

<h2>CreateResult</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script> 
<script type="text/javascript" src="../../Scripts/jquery-1.5.1.js"></script>

<script type="text/javascript">

    $(document).ready(function () {
        $("#btnSubmit").click(function () {
            var mylsit1, mylist2, opponetVal, blackBallPlayerVal, blackBall;
            mylsit1 = $("#myList1").val();
            mylist2 = $("#myList2").val();
            blackBallPlayerVal = $("#BlackBallPlayer option:selected").val();
            blackBall = $("#blackBall").val();
            opponetVal = $("#Opponent option:selected").val();

            if (blackBallPlayerVal == "Choose") {
                alert("select the player name who sink the black ball");
                return false;
            }
            if (opponetVal == "Choose") {
                alert("Select Opponent");
                return false;
            }
            if (blackBall.length == 0) {
                alert("Black Ball is null");
                return false;
            }
            if (mylsit1.length == 0 || mylist2.length == 0) {
                alert("Balls are null");
                return false;
            }
            return true;
        });
    });    
  
</script>

@using (Html.BeginForm("CreateResult", "Result", FormMethod.Post, new { @id = Model.Id }))
{
   @Html.ValidationSummary(true)
    <table>
        <tr>
            <td>
                First Player :  
            </td>
            <td>             
                <h3>@Model.FirstName @Model.LastName</h3>
            </td>
            
            <td>
                Second Player :
            </td>
            <td>
                @Html.ValidationMessageFor(model => model.SelectedPLayerValue)
                @Html.DropDownList("Opponent", Model.SelectedPLayerValue)
            </td>
        </tr>
       
        <tr>
            <td>
                Balls
            </td>
            <td>            
                @Html.DropDownList("myList1", new SelectList(new[] { "0", "1", "2", "3", "4", "5", "6", "7" }), "Choose")        
            </td>
            <td>
                Balls
            </td>
            <td>
                @Html.DropDownList("myList2", new SelectList(new[] { "0", "1", "2", "3", "4", "5", "6", "7" }), "Choose")          
            </td>          
        </tr>
    <tr>
        <td>Who Sank black ball? </td>
            <td>
                @Html.ValidationMessageFor(model => model.BalckBallPLayerValue)
                @Html.DropDownList("BlackBallPlayer", Model.BalckBallPLayerValue)
            </td>
      
        <td>Black Ball</td>
   
            
            
               <td>
                @Html.DropDownList("blackBall", new SelectList(new[] { "8" }), "Choose")          
            </td> 
          

        </tr>
    </table>
    <p>
        <input type="submit" id ="btnSubmit" value="Create" />
    </p>
    
    <div>
        @Html.ActionLink("Back to List", "Index", "Player")
    </div>
}

MongoDBPool/Views/Result/DisplayResults.cshtml
@model MongoDBPool.ViewModels.DisplayResultView

@{
    ViewBag.Title = "Player Results";
}
<input name = "name" type="hidden" value = "@ViewBag.name"/>

<h2>Player Results </h2>
@using (Html.BeginForm("Edit", "Player", FormMethod.Post, new {}))
{
    <p>
 
  
    </p>

    <div style="float: right">
        <table >
    
            <tr>
                <th>
                     Host Name
                </th>
                <th></th>
                  
                <th>
                  Ball Left
                </th>
                <th></th>
                <th>     
                    Opponent  Name
                </th>  
                <th></th>
                <th>
                    Ball Left
                </th>
                <th></th>  
                <th>
                    Date
                </th>  
            </tr>
            @foreach (var item2 in Model.HostResults)
            {

                <tr>
                    <td>
                        @Html.DisplayFor(modelitem2 => item2.HostName) 
                    </td>
                    <td></td>
                    <td>
                        @Html.DisplayFor(modelitem2 => item2.HosBallsLeft)
                    </td>
                    <td></td>   
                    <td>
                        @Html.DisplayFor(modelitem2 => item2.OppnetName)
                    </td>
                    <td></td>
                    
                     <td>
                        @Html.DisplayFor(modelitem2 => item2.OppnetBallsLeft)
                    </td>
                    <td></td>
                    
                    
                    <td>
                        @Html.DisplayFor(modelitem => item2.Date)
                    </td>
                </tr>
            }
    
    
    
        </table>
    </div>
}

MongoDBPool/Views/Result/Edit.cshtml
@model MongoDBPool.Models.Results

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm("Edit", "Result", FormMethod.Post, new { }))
{
    @Html.HiddenFor(model => model._id)

    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Results</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.HosBallsLeft)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.HosBallsLeft)
            @Html.ValidationMessageFor(model => model.HosBallsLeft)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.OppnetBallsLeft)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.OppnetBallsLeft)
            @Html.ValidationMessageFor(model => model.OppnetBallsLeft)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MongoDBPool/Views/Result/Index.cshtml
@model IEnumerable<MongoDBPool.Models.Results>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Index","Player")
</p>
<table>
    <tr>
        <th>
          Host Name
        </th>
        <th>
          Balls Lefts
        </th>
        <th>
           Opponent Name
        </th>
        <th>
          Host BallsLeft
        </th>
        <th>
           Date
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>     
       <td>
            @Html.DisplayFor(modelItem => item.HostName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OppnetBallsLeft)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OppnetName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OppnetBallsLeft)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { controller = "Result", id = item._id.ToString() }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>